# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2019-07-15 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publication_date']},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default=5, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='news_source',
            field=models.CharField(choices=[('DN', 'DAILY NATION'), ('BD', 'BUSINESS DAILY')], default=4, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='publication_date',
            field=models.DateField(default=9878),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
