# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_auto_20190725_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_source',
            field=models.CharField(choices=[('DN', 'THE DAILY NATION'), ('BD', 'THE BUSINESS DAILY'), ('EA', 'THE EAST AFRICAN')], max_length=100),
        ),
    ]
