# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-31 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0008_auto_20191122_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_source',
            field=models.CharField(choices=[('DN', 'THE DAILY NATION'), ('BD', 'THE BUSINESS DAILY'), ('EA', 'THE EAST AFRICAN'), ('CT', 'THE CITIZEN'), ('SM', 'THE DAILY STANDARD'), ('DM', 'THE DAILY MONITOR')], max_length=100),
        ),
    ]
