# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-26 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0010_auto_20200323_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_source',
            field=models.CharField(choices=[('DN', 'THE DAILY NATION'), ('BD', 'THE BUSINESS DAILY'), ('EA', 'THE EAST AFRICAN'), ('CT', 'THE CITIZEN'), ('SM', 'THE DAILY STANDARD'), ('DM', 'THE DAILY MONITOR'), ('TS', 'THE STAR KENYA')], max_length=100),
        ),
    ]
