# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-07 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0011_auto_20200327_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.CharField(max_length=5)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
