# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-07 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0012_newssource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='news_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawl.NewsSource'),
        ),
    ]
