# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-07 17:18
from __future__ import unicode_literals

from django.db import migrations

def change_news_source_to_foreign_key(apps, schema_editor):
	Article = apps.get_model('crawl', 'Article')
	NewsSource = apps.get_model('crawl', 'NewsSource')

	for article in Article.objects.all():
		source = NewsSource.objects.get(slug=article.news_source)
		article.source = source
		article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0013_article_source'),
    ]

    operations = [
    migrations.RunPython(change_news_source_to_foreign_key),
    ]
