# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-07 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0014_change_news_source_to_foreign_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='news_source',
        ),
    ]
