# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-07 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0015_remove_article_news_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='source',
            new_name='news_source',
        ),
    ]
