# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-08 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0016_auto_20200407_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_articles', models.IntegerField(blank=True, null=True)),
                ('crawl_error', models.TextField(blank=True, null=True)),
                ('crawl_time', models.DateTimeField(auto_now_add=True)),
                ('news_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawl.NewsSource')),
            ],
        ),
    ]
