# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0017_crawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawl',
            name='status',
            field=models.CharField(choices=[('crawling', 'Crawling'), ('error', 'Error'), ('good', 'Good'), ('start', 'Start')], default='start', max_length=30),
        ),
    ]
