# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-15 11:46
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0018_crawl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='new_author',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=500), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='crawl',
            name='total_articles',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
