# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-15 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0019_auto_20200415_1446'),
    ]

    operations = [
    ]
