# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-15 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0020_create_new_author_with_array_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
