# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-15 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0021_remove_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='new_author',
            new_name='author',
        ),
    ]
