# Generated by Django 2.2.12 on 2020-06-02 23:27

import requests
from bs4 import BeautifulSoup
from django.db import migrations
from django.utils import timezone
from habari.apps.crawl.crawlers.AbstractBaseCrawler import sanitize_author_string

def sanitize_dn_authors(apps, schema_editor):
	yesterday = timezone.now() - timezone.timedelta(days=2)
	Article = apps.get_model('crawl', 'Article')

	startswith_newsplex = ('https://www.nation.co.ke/dailynation/health',
	  'https://www.nation.co.ke/newsplex',
	  'https://www.nation.co.ke/dailynation/brand-book',
	  'https://www.nation.co.ke/gender',
	  'https://www.nation.co.ke/dailynation/healthy-nation',
	  )

	for article in Article.objects.filter(news_source__slug='DN',timestamp__gte=yesterday):
		request = requests.get(article.article_url)
		if request.status_code == 200:
			soup = BeautifulSoup(request.content, 'html.parser')
            if article.article_url.startswith(startswith_newsplex):
                author = [sanitize_author_string(
        a.get_text().strip()) for a in soup.select('.byline figcaption h6')]
            elif article.article_url.startswith('https://www.nation.co.ke/nationprime/'):
                author = [sanitize_author_string(
        a.get_text().strip()) for a in soup.select('.article-content h6.name')]
            else:
                author = [sanitize_author_string(
        a.get_text().strip()) for a in soup.select('section.author strong')]
        article.author = authorarticle.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0023_sanitize_dn_titles'),
    ]

    operations = [
    migrations.RunPython(sanitize_dn_authors),
    ]
