# Generated by Django 2.2.12 on 2020-06-03 10:29
import re
from django.db import migrations

def fix_bd_author_splits(apps, schema_editor):
	Article = apps.get_model('crawl', 'Article')

	for article in Article.objects.filter(news_source__slug='BD'):
		author = []
		for a in article.author:
			author_list = re.split(' & | and |, ', a.lower())
			new_authors = [author.append(a) for a in map(lambda x:x.strip().upper(), author_list)]

		article.author = author
		article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0024_update_dn_authors'),
    ]

    operations = [
    migrations.RunPython(fix_bd_author_splits),
    ]
