# Generated by Django 2.2.12 on 2020-07-11 20:14
import requests
from bs4 import BeautifulSoup
from django.db import migrations
from habari.apps.crawl.crawlers import AbstractBaseCrawler

def sanitize_ea_authors(apps, schema_editor):
	base_class = AbstractBaseCrawler('EA')
	Article = apps.get_model('crawl', 'Article')

	articles = Article.objects.filter(news_source__slug='EA', author=[])
	for article in articles:
		request = requests.get(article.article_url)
		if request.status_code == 200:
			soup = BeautifulSoup(request.content, 'lxml')

			author_list = soup.select('.author strong')
			author = base_class.sanitize_author_iterable(author_list)
		article.author = author
		article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0026_fix_concatenated_authors'),
    ]

    operations = [
    migrations.RunPython(sanitize_ea_authors)
    ]
