# Generated by Django 2.2.12 on 2020-07-13 16:54
import re
import requests
from bs4 import BeautifulSoup
from django.db import migrations

def sanitize_sm_authors(apps, schema_editor):
	Article = apps.get_model('crawl', 'Article')

	articles = Article.objects.filter(news_source__slug='SM', author=[])
	for article in articles:
		request = requests.get(article.article_url)
		if request.status_code == 200:
			soup = BeautifulSoup(request.content, 'lxml')
			try:
				author = [a.strip().upper() for a in soup.select_one('.article-meta a').get_text().split(' and ') if a is not '']
			except AttributeError:
				try:
					author = [a.strip().upper() for a in soup.select('div .io-hidden-author').get_text()]
				except AttributeError:
					try:
						author = [a.strip().upper() for a in soup.select_one('.small.text-muted.mb-3 a').get_text().lower().split(' and ')]
					except AttributeError:
						try:
							author = [a.strip().upper() for a in re.split('&| and |, ', soup.find("meta", attrs={'name':'author'}).get('content').lower())]
						except AttributeError:
							author = []
		if author == [''] or author == [':']:
			author = []

		article.author = author
		article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0027_update_ea_authors'),
    ]

    operations = [
    migrations.RunPython(sanitize_sm_authors)
    ]
