# Generated by Django 2.2.12 on 2020-11-17 21:29

from django.db import migrations

def remove_author_duplicates(apps, schema_editor):
	Article = apps.get_model('crawl', 'Article')
	articles = Article.objects.filter(news_source__slug='BD')

	for article in articles:
		updated_authors = set(article.author)
		article.author = list(updated_authors)
		article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0028_update_SM_author'),
    ]

    operations = [
    migrations.RunPython(remove_author_duplicates)
    ]
