# Generated by Django 2.2.12 on 2020-11-17 21:50

from django.db import migrations

def remove_empty_author_strings(apps, schema_editor):
    Article = apps.get_model('crawl', 'Article')
    articles = Article.objects.filter(author__contains=[''])

    for article in articles:
        authors = [i for i in article.author if i]
        article.author = authors
        article.save()
		
class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0029_remove_duplicate_author_entries'),
    ]

    operations = [
    migrations.RunPython(remove_empty_author_strings)
    ]
