# Generated by Django 2.2.12 on 2020-12-07 09:01

from django.db import migrations
from habari.apps.crawl.crawlers.dmcrawler import DMCrawler

def update_empty_daily_monitor_author_lists(apps, schema_editor):
	Article = apps.get_model('crawl', 'Article')
	articles = Article.objects.filter(author__len=0,news_source__slug='DM')

	crawler_class = DMCrawler()
	for article in articles:
		article_details = {'article_url':article.article_url}
		update_details = crawler_class.update_article_details(article_details)
		article.author = update_details['author']
		article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0030_remove_empty_authors_using_migration'),
    ]

    operations = [
    migrations.RunPython(update_empty_daily_monitor_author_lists)
    ]
